<?php
$name=$_POST["name"];
$birthday=$_POST["birthday"];
$gender=$_POST["gender"];
$language=$_POST["language"];
$oldid=$_POST["oldid"];
/*echo $oldid;
die();*/
$oldphoto=$_POST["oldprofile"];
$oldlogo=$_POST["oldlogo"];
$profile=$_FILES["photo"];
$logo=$_FILES["logo"];

if($profile["size"]>0){
	/*echo"yes";*/
	$photoname=$profile["name"];
	$photopath="image/".time().$photoname;
	move_uploaded_file($profile["tmp_name"],$photopath);
}else
{
	$photopath=$oldphoto;
}
if($logo["size"]>0){
	/*echo"yes";*/
	$logoname=$logo["name"];
	$logopath="image/logo/".time().$logoname;
	move_uploaded_file($logo["tmp_name"],$logopath);
}
else
{
	$logopath=$oldlogo;
}
$member=['profile'=>$photopath,'logo'=>$logopath,'name'=>$name,'birthday'=>$birthday,'gender'=>$gender,'Language'=>$language];
$file=file_get_contents('list.json');
$file_array=json_decode($file,true);
$file_array[$oldid]=$member;
$file_string=json_encode($file_array,JSON_PRETTY_PRINT);
file_put_contents("list.json",$file_string)?
header('location:index.php'):print("fail to update");
?>